# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gcs.ui'
#
# Created: Thu Oct  9 16:35:40 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1493, 736)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1247, 736))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pathDisplayLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathDisplayLabel.sizePolicy().hasHeightForWidth())
        self.pathDisplayLabel.setSizePolicy(sizePolicy)
        self.pathDisplayLabel.setMinimumSize(QtCore.QSize(200, 10))
        self.pathDisplayLabel.setStyleSheet("text-align:\"center\"")
        self.pathDisplayLabel.setText("")
        self.pathDisplayLabel.setObjectName("pathDisplayLabel")
        self.gridLayout.addWidget(self.pathDisplayLabel, 0, 0, 1, 1)
        self.fullSizeImageScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.fullSizeImageScrollArea.sizePolicy().hasHeightForWidth())
        self.fullSizeImageScrollArea.setSizePolicy(sizePolicy)
        self.fullSizeImageScrollArea.setMinimumSize(QtCore.QSize(200, 200))
        self.fullSizeImageScrollArea.setWidgetResizable(True)
        self.fullSizeImageScrollArea.setObjectName("fullSizeImageScrollArea")
        self.midWidget = QtWidgets.QWidget()
        self.midWidget.setGeometry(QtCore.QRect(0, 0, 1355, 553))
        self.midWidget.setMinimumSize(QtCore.QSize(1059, 519))
        self.midWidget.setObjectName("midWidget")
        self.fullSizeImageScrollArea.setWidget(self.midWidget)
        self.gridLayout.addWidget(self.fullSizeImageScrollArea, 1, 0, 1, 1)
        self.imageAttributesFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageAttributesFrame.sizePolicy().hasHeightForWidth())
        self.imageAttributesFrame.setSizePolicy(sizePolicy)
        self.imageAttributesFrame.setMinimumSize(QtCore.QSize(120, 200))
        self.imageAttributesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageAttributesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageAttributesFrame.setObjectName("imageAttributesFrame")
        self.lastSyncLCDNumber = QtWidgets.QLCDNumber(self.imageAttributesFrame)
        self.lastSyncLCDNumber.setGeometry(QtCore.QRect(60, 0, 64, 23))
        self.lastSyncLCDNumber.setMinimumSize(QtCore.QSize(64, 23))
        self.lastSyncLCDNumber.setStyleSheet("font: 13pt \".Lucida Grande UI\";background-color:rgb(255,255,255);")
        self.lastSyncLCDNumber.setObjectName("lastSyncLCDNumber")
        self.nowLCDNumber = QtWidgets.QLCDNumber(self.imageAttributesFrame)
        self.nowLCDNumber.setGeometry(QtCore.QRect(60, 30, 64, 23))
        self.nowLCDNumber.setStyleSheet("font: 13pt \".Lucida Grande UI\";background-color:rgb(255,255,255);")
        self.nowLCDNumber.setObjectName("nowLCDNumber")
        self.label = QtWidgets.QLabel(self.imageAttributesFrame)
        self.label.setGeometry(QtCore.QRect(0, 0, 62, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.imageAttributesFrame)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 62, 16))
        self.label_2.setMinimumSize(QtCore.QSize(62, 16))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.imageAttributesFrame, 1, 1, 1, 1)
        self.thumbnailScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.thumbnailScrollArea.setMinimumSize(QtCore.QSize(200, 100))
        self.thumbnailScrollArea.setWidgetResizable(True)
        self.thumbnailScrollArea.setObjectName("thumbnailScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1340, 129))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(1059, 129))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.thumbnailScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.thumbnailScrollArea, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1493, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.syncInfoToolbar = QtWidgets.QToolBar(MainWindow)
        self.syncInfoToolbar.setObjectName("syncInfoToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.syncInfoToolbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LastSync"))
        self.label_2.setText(_translate("MainWindow", "Now"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.syncInfoToolbar.setWindowTitle(_translate("MainWindow", "toolBar_2"))

