# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gcs.ui'
#
# Created: Thu Oct  9 17:10:10 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.pathDisplayLabel = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathDisplayLabel.sizePolicy().hasHeightForWidth())
        self.pathDisplayLabel.setSizePolicy(sizePolicy)
        self.pathDisplayLabel.setMinimumSize(QtCore.QSize(200, 10))
        self.pathDisplayLabel.setStyleSheet("text-align:\"center\"")
        self.pathDisplayLabel.setText("")
        self.pathDisplayLabel.setObjectName("pathDisplayLabel")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.fullSizeImageScrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.fullSizeImageScrollArea.sizePolicy().hasHeightForWidth())
        self.fullSizeImageScrollArea.setSizePolicy(sizePolicy)
        self.fullSizeImageScrollArea.setMinimumSize(QtCore.QSize(200, 200))
        self.fullSizeImageScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fullSizeImageScrollArea.setWidgetResizable(True)
        self.fullSizeImageScrollArea.setObjectName("fullSizeImageScrollArea")
        self.midWidget = QtWidgets.QWidget()
        self.midWidget.setGeometry(QtCore.QRect(-40, 0, 1059, 519))
        self.midWidget.setMinimumSize(QtCore.QSize(1059, 519))
        self.midWidget.setObjectName("midWidget")
        self.fullSizeImageScrollArea.setWidget(self.midWidget)
        self.imageAttributesFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageAttributesFrame.sizePolicy().hasHeightForWidth())
        self.imageAttributesFrame.setSizePolicy(sizePolicy)
        self.imageAttributesFrame.setMinimumSize(QtCore.QSize(130, 200))
        self.imageAttributesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageAttributesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageAttributesFrame.setObjectName("imageAttributesFrame")
        self.formLayout = QtWidgets.QFormLayout(self.imageAttributesFrame)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.imageAttributesFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lastSyncLCDNumber = QtWidgets.QLCDNumber(self.imageAttributesFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastSyncLCDNumber.sizePolicy().hasHeightForWidth())
        self.lastSyncLCDNumber.setSizePolicy(sizePolicy)
        self.lastSyncLCDNumber.setMinimumSize(QtCore.QSize(0, 0))
        self.lastSyncLCDNumber.setStyleSheet("font: 13pt \".Lucida Grande UI\";background-color:rgb(255,255,255);")
        self.lastSyncLCDNumber.setObjectName("lastSyncLCDNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lastSyncLCDNumber)
        self.nowLCDNumber = QtWidgets.QLCDNumber(self.imageAttributesFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nowLCDNumber.sizePolicy().hasHeightForWidth())
        self.nowLCDNumber.setSizePolicy(sizePolicy)
        self.nowLCDNumber.setStyleSheet("font: 13pt \".Lucida Grande UI\";background-color:rgb(255,255,255);")
        self.nowLCDNumber.setObjectName("nowLCDNumber")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nowLCDNumber)
        self.label_2 = QtWidgets.QLabel(self.imageAttributesFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.thumbnailScrollArea = QtWidgets.QScrollArea(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbnailScrollArea.sizePolicy().hasHeightForWidth())
        self.thumbnailScrollArea.setSizePolicy(sizePolicy)
        self.thumbnailScrollArea.setMinimumSize(QtCore.QSize(200, 100))
        self.thumbnailScrollArea.setWidgetResizable(True)
        self.thumbnailScrollArea.setObjectName("thumbnailScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1059, 129))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(1059, 129))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.thumbnailScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.splitter_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.syncInfoToolbar = QtWidgets.QToolBar(MainWindow)
        self.syncInfoToolbar.setObjectName("syncInfoToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.syncInfoToolbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LastSync"))
        self.label_2.setText(_translate("MainWindow", "Now"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.syncInfoToolbar.setWindowTitle(_translate("MainWindow", "toolBar_2"))

